# Generated by Django 3.0.1 on 2020-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_auto_20200227_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='work_experience',
            field=models.PositiveIntegerField(),
        ),
    ]
